blank_issues_enabled: false
contact_links:
  - name: GitHub Community Support
    url: https://github.com/community
    about: Please ask and answer questions here.
  - name: Discussions
    url: https://github.com/your-username/task-manager/discussions
    about: General discussions and questions about the project.
